
package panti_asuhan;

import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RIZKY ALFARIZI 
 * jangan lupa kerjain tugas sambil dengerin lagu kangen band
 */

public class ANAK_ASUH extends javax.swing.JFrame {
    
 Connection konek;
 public Statement cn;
 String tgl_lahir,tempatlahir,tgl_masuk,id,nama,jk,agama,pendidikan;

    
public void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Sukses Driver JDBC Ditemukan....!");
        try {
            String url =
            "jdbc:mysql://localhost/pantiasuhan?user=root&password=";
             konek = DriverManager.getConnection(url);
             cn=konek.createStatement();
             System.out.println("Sukses Koneksi...");
         } catch (SQLException se) {
            System.out.println(" Gagal Koneksi = " + se);
             System.exit(0);
     }
         } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(null, "Class Tidak ditemukan...Error: " + cnfe);
            System.exit(0);
 }
    
 }

//untuk menampilkan data
public void tampildata(){
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID");
    tabel.addColumn("Nama ");
    tabel.addColumn("Jenis Kelamin");
    tabel.addColumn("Tempat Lahir");
    tabel.addColumn("Tanggal Lahir");
    tabel.addColumn("Agama");
    tabel.addColumn("Pendidikan");
    tabel.addColumn("Tanggal Masuk");
    
    try{
        String sql="Select * from anak_asuh"; //perintah menampilkan isi tabe;
        Statement stt=(Statement) konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_anak"), //Sesuai nama tabel di database
            res.getString("nama_anak"),
            res.getString("jk"),
            res.getString("tempat_lahir"),
            res.getString("tanggal_lahir"),
            res.getString("agama"),
            res.getString("pendidikan"),
            res.getString("tanggal_masuk")});
            jTable1.setModel(tabel);
        }
    }
    catch(Exception e){
                }
    }
        
    
public void clear(){
    jTextField1.setText("");
    jTextField2.setText("");
    buttonGroup1.clearSelection();
    jTextField3.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jDateChooser1.setDate(null);
    jDateChooser2.setDate(null);
    jTextField1.setEnabled(true);
}
    public ANAK_ASUH() {
        initComponents();
        koneksi();  
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        close = new javax.swing.JButton();
        show = new javax.swing.JButton();
        print = new javax.swing.JButton();
        back = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel5.setText("AGAMA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 80, 30));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel6.setText("PENDIDIKAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 120, 30));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel7.setText("TANGGAL MASUK");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 130, 50));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel8.setText("TEMPAT LAHIR");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 130, 30));

        jTextField3.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 250, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel9.setText("TANGGAL LAHIR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 150, 30));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 250, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 20, 30));

        jTextField1.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 250, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setText("NAMA ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 80, 30));

        jTextField2.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 250, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setText("JENIS KELAMIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 120, 50));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jRadioButton1.setText("LAKI-LAKI");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, 50));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jRadioButton2.setText("PEREMPUAN");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, 50));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAMA", "JENIS KELAMIN", "TEMPAT LAHIR", "TANGGAL LAHIR", "AGAMA", "PENDIDIKAN", "TANGGAL MASUK"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(30, 178, 166));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 700, 140));

        jComboBox1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---AGAMA---", "ISLAM", "KRISTEN PROTESTAN", "KRISTEN KATOLIK", "HINDU", "BUDHA", "KONG HU CHU" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 250, -1));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 250, -1));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bakti Luhur peduli sesama");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BAKTI   ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" LUHUR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/LOGO.png"))); // NOI18N
        jLabel14.setToolTipText("");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 70));

        jLabel10.setBackground(new java.awt.Color(30, 178, 166));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 620));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 178, 166));
        jLabel16.setText("DATA ANAK ASUH");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 178, 166));
        jLabel17.setText("____");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 280, 60));

        save.setBackground(new java.awt.Color(30, 155, 133));
        save.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 191, 26));

        update.setBackground(new java.awt.Color(30, 155, 133));
        update.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("EDIT");
        update.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 191, 26));

        delete.setBackground(new java.awt.Color(30, 155, 133));
        delete.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 191, 26));

        clear.setBackground(new java.awt.Color(30, 155, 133));
        clear.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 191, 26));

        close.setBackground(new java.awt.Color(30, 155, 133));
        close.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 191, 26));

        show.setBackground(new java.awt.Color(30, 155, 133));
        show.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        show.setForeground(new java.awt.Color(255, 255, 255));
        show.setText("TAMPILKAN DATA");
        show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 191, 26));

        print.setBackground(new java.awt.Color(30, 155, 133));
        print.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("CETAK");
        print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 191, 26));

        back.setBackground(new java.awt.Color(30, 178, 166));
        back.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon("D:\\UNP\\Semester 4\\Buk yani\\Ikon\\home1.png")); // NOI18N
        back.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        back.setBorderPainted(false);
        back.setContentAreaFilled(false);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 70, 70));

        search.setBackground(new java.awt.Color(30, 178, 166));
        search.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setIcon(new javax.swing.ImageIcon("D:\\UNP\\Semester 4\\Buk yani\\Ikon\\search1.png")); // NOI18N
        search.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        search.setBorderPainted(false);
        search.setContentAreaFilled(false);
        search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 50, 50));

        jTextField4.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 191, 30));

        jComboBox2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PENDIDIKAN---", "TK/PAUD", "SD/MI", "SMP/MTS", "SMA/SMK/MAN" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 250, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 970, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID");
    tabel.addColumn("Nama");
    tabel.addColumn("Jenis Kelamin");
    tabel.addColumn("Tempat Lahir");
    tabel.addColumn("Tanggal Lahir");
    tabel.addColumn("Agama");
    tabel.addColumn("Pendidikan");
    tabel.addColumn("Tanggal Masuk");
    
    try{
        String sql="Select*from anak_asuh where id_anak like '%"+
                jTextField4.getText()+"%' or nama_anak like '%"+
                jTextField4.getText()+"%' or tempat_lahir like '%"+
                jTextField4.getText()+"%' or tanggal_lahir like '%"+
                jTextField4.getText()+"%' or jk like '%"+
                jTextField4.getText()+"%' or agama like '%"+
                jTextField4.getText()+"%' or pendidikan like '%"+
                jTextField4.getText()+"%' or tanggal_masuk like '%"+
                jTextField4.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_anak"),
            res.getString("nama_anak"),
            res.getString("jk"),
            res.getString("tempat_lahir"),
            res.getString("tanggal_lahir"),
            res.getString("agama"),
            res.getString("pendidikan"),
            res.getString("tanggal_masuk"),});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
    }
    }//GEN-LAST:event_searchActionPerformed

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_saveMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
      id=jTextField1.getText();
      nama=jTextField2.getText();
      tempatlahir= jTextField3.getText();
      jk=null; 

if (id.equals("")) {
 JOptionPane.showMessageDialog(null, "ID TIDAK BOLEH KOSONG");
 jTextField1.requestFocus();
 }else {
     try {
 String sql = "Insert Into anak_asuh values(?,?,?,?,?,?,?,?)";
 PreparedStatement stat = konek.prepareStatement(sql);
 try {
 stat.setString(1, id);
 stat.setString(2, nama);
 if (jRadioButton1.isSelected()){
            jk="LAKI-LAKI";
            }else if(jRadioButton2.isSelected()){
            jk="PEREMPUAN";
            }
 stat.setString(5, jk);
 stat.setString(3, jTextField3.getText());
 stat.setString(4,tgl_lahir);
 stat.setString(6, String.valueOf(jComboBox1.getSelectedItem()));
 stat.setString(7, String.valueOf(jComboBox2.getSelectedItem()));
 stat.setString(8,tgl_masuk);
 stat.executeUpdate();
 JOptionPane.showMessageDialog(null, "Data Tersimpan.....");
 } catch (SQLException se) {
 System.out.println("Gagal Menyimpan.." + se);
 JOptionPane.showMessageDialog(null, "Yang Anda Masukkan Telah Ada..\nGagal Disimpan..Coba Lagi \npesan Error :\n" +se);
 jTextField1.requestFocus();
 }
 } catch (Exception se) {
 }
 }
    }//GEN-LAST:event_saveActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if(jDateChooser1.getDate()!=null){
            SimpleDateFormat tgl=new SimpleDateFormat("yyyy-MM-dd");
            tgl_lahir = tgl.format(jDateChooser1.getDate());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
                if(jDateChooser2.getDate()!=null){
            SimpleDateFormat tgl=new SimpleDateFormat("yyyy-MM-dd");
            tgl_masuk = tgl.format(jDateChooser2.getDate());}
    }//GEN-LAST:event_jDateChooser2PropertyChange

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new MAINMENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int table =jTable1.getSelectedRow();
        String a = jTable1.getValueAt(table, 0).toString(); //id
        String b = jTable1.getValueAt(table, 1).toString(); //nama
        String c = jTable1.getValueAt(table, 2).toString(); //jk
        String d = jTable1.getValueAt(table, 3).toString(); //tempatlahir
        //tgl lahir
        try{
            java.util.Date tgl= new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable1.getValueAt(table,4));
            jDateChooser1.setDate(tgl);
        } catch (Exception se){
        }
        String f = jTable1.getValueAt(table, 5).toString();//agama
        String g = jTable1.getValueAt(table, 6).toString();//pendidikan
        //tgl masuk
        try{
            java.util.Date tgl= new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable1.getValueAt(table,7));
            jDateChooser2.setDate(tgl);
        } catch (Exception se){
        }
        
        jTextField1.setText(a);
        jTextField2.setText(b);
        if("LAKI-LAKI".equals(c)|"Laki-laki".equals(c)){
            jRadioButton1.setSelected(true);
        }else{
            jRadioButton2.setSelected(true);
        }
        if("PEREMPUAN".equals(c)|"Perempuan".equals(c)){
            jRadioButton2.setSelected(true);
        }else{
            jRadioButton1.setSelected(true);
        }
        jTextField3.setText(d);
        jComboBox1.setSelectedItem(f);
        jComboBox2.setSelectedItem(g);
        
        jTextField1.setEnabled(false);
        jTextField2.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        tampildata();
    }//GEN-LAST:event_showActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // DELETE DATA 
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Menghapus Data Ini?","Confirmation",
                JOptionPane.YES_NO_CANCEL_OPTION); //panel konfirmasi
        
        if(ok==0)
        {
            try{
                String sql="Delete from anak_asuh where id_anak='"+jTextField1.getText()+"'";
                PreparedStatement st=konek.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"DELETE DATA SUKSES");
            }
            catch (Exception e){
            }
        }
        tampildata();
        clear();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // UPDATE DATA    
        id=jTextField1.getText();
        nama=jTextField2.getText();
        tempatlahir= jTextField3.getText();
        if (jRadioButton1.isSelected())
        {jk=jRadioButton1.getText();}
        else if (jRadioButton2.isSelected())
        {jk=jRadioButton2.getText();}
        else
        {jk="";}
                       
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
            jTextField1.requestFocus();
        }else{
            try{
                String sql="Update anak_asuh set nama_anak='"+nama+"',"
                        +"jk= '"+jk +"',"
                        +"tempat_lahir = '"+tempatlahir+"',"
                        +"tanggal_lahir = '"+tgl_lahir+"',"
                        +"agama= '"+jComboBox1.getSelectedItem()+"',"
                        +"pendidikan = '"+jComboBox2.getSelectedItem()+"',"
                        +"tanggal_masuk = '"+tgl_masuk+""
                        +"'where id_anak= '"+id+"'";
                cn.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUPDATE");   
            }
            catch (Exception se){
                JOptionPane.showMessageDialog(null, "GAGAL MENGUBAH DATA"+se);
                jTextField1.requestFocus();
            }
        }
        clear();
        tampildata();
    }//GEN-LAST:event_updateActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
    this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        int tanya=JOptionPane.showConfirmDialog(null,"INGIN MENCETAK DATA ?","KONFIRMASI",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(tanya==0){
            new CetakAnakAsuh().setVisible(true);
            this.dispose();
        }
        else if(tanya==1){
            new ANAK_ASUH().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_printActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID");
    tabel.addColumn("Nama");
    tabel.addColumn("Jenis Kelamin");
    tabel.addColumn("Tempat Lahir");
    tabel.addColumn("Tanggal Lahir");
    tabel.addColumn("Agama");
    tabel.addColumn("Pendidikan");
    tabel.addColumn("Tanggal Masuk");
    
    try{
        String sql="Select*from anak_asuh where id_anak like '%"+
                jTextField4.getText()+"%' or nama_anak like '%"+
                jTextField4.getText()+"%' or tempat_lahir like '%"+
                jTextField4.getText()+"%' or tanggal_lahir like '%"+
                jTextField4.getText()+"%' or jk like '%"+
                jTextField4.getText()+"%' or agama like '%"+
                jTextField4.getText()+"%' or pendidikan like '%"+
                jTextField4.getText()+"%' or tanggal_masuk like '%"+
                jTextField4.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_anak"),
            res.getString("nama_anak"),
            res.getString("jk"),
            res.getString("tempat_lahir"),
            res.getString("tanggal_lahir"),
            res.getString("agama"),
            res.getString("pendidikan"),
            res.getString("tanggal_masuk"),});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
    }
    }//GEN-LAST:event_jTextField4KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ANAK_ASUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ANAK_ASUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ANAK_ASUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ANAK_ASUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ANAK_ASUH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton print;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JButton show;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private Date convertUtilDateToSqlDate(java.util.Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
