/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panti_asuhan;

import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import javax.swing.text.EditorKit;
import javax.swing.text.html.HTMLEditorKit;

public class CetakDonasi extends javax.swing.JFrame {

Connection konek;
public Statement cn;

public void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Sukses Driver JDBC Ditemukan....!");
        try {
            String url =
            "jdbc:mysql://localhost/pantiasuhan?user=root&password=";
             konek = DriverManager.getConnection(url);
             cn=konek.createStatement();
             System.out.println("Sukses Koneksi...");
         } catch (SQLException se) {
            System.out.println(" Gagal Koneksi = " + se);
             System.exit(0);
     }
         } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(null, "Class Tidak ditemukan...Error: " + cnfe);
            System.exit(0);
 }
}

public void cetak(){
    String html =
            "<center><br><b><font face='Dubai' size='10' color='#1EB2A6'>PANTI ASUHAN BAKTI LUHUR</font></b><br>"
            +"<font face='Montserrat' size='5' color='#1EB2A6'>Jl.Timbuktu  No 17 Padang</center><br>"
            +"<br><b><font color='#1EB2A6'>-------------------------------------------------------------------------------------------------------------------------------</font><br>"
            +"<b><font face='dubai' color='#1EB2A6'>DATA DONASI</b><br>"
            +"<br>"
            +"<table width='100%' border='0' cellpadding='7' cellspacing='1'"
            +"<tr bgcolor='#1EB2A6' align='center'>"
                +"<td><font color='white'> <strong> ID DONATUR </strong> </td>"
                +"<td><font color='white'> <strong> NAMA DONATUR </strong> </td>"
                +"<td><font color='white'> <strong> ID PEGAWAI </strong> </td>"
                +"<td><font color='white'> <strong> NAMA PEGAWAI </strong> </td>"
                +"<td><font color='white'> <strong> BENTUK </strong> </td>"
                +"<td><font color='white'> <strong> KETERANGAN </strong> </td>"
                +"</tr>";
    try{
        koneksi();
        String sql="Select *from donasi";//from nama tabel di mysql
        PreparedStatement stat=(PreparedStatement) konek.prepareStatement(sql);
        ResultSet set=stat.executeQuery(sql);
        while(set.next()){
            html = html + "<tr bgcolor='#cff1ef' align='center'>"
                            +"<td>"+set.getString("id_donatur")+"</td>"
                            +"<td>"+set.getString("nama_donatur")+"</td>"
                            +"<td>"+set.getString("id_pegawai")+"</td>"
                            +"<td>"+set.getString("nama_pegawai")+"</td>"
                            +"<td>"+set.getString("bentuk")+"</td>"
                            +"<td>"+set.getString("keterangan")+"</td>"
                           +"</tr>";
        }
            EditorKit x = new HTMLEditorKit();
            jEditorPane1.setEditorKit(x);
            jEditorPane1.setText(html);            
    } catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
            }
    public CetakDonasi() {
        initComponents();
        koneksi();
        cetak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        print = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(841, 458));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 804, 371));

        print.setBackground(new java.awt.Color(30, 155, 133));
        print.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.setBorder(null);
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printMouseClicked(evt);
            }
        });
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 191, 26));

        cancel.setBackground(new java.awt.Color(30, 155, 133));
        cancel.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("CANCEL");
        cancel.setBorder(null);
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 191, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printMouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try{
            boolean complete=jEditorPane1.print();
            if (complete){
                JOptionPane.showMessageDialog(null, "BERHASIL");
            } else {
                JOptionPane.showMessageDialog(null,"GAGAL!");
            }
        }   catch (PrinterException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int tanya=JOptionPane.showConfirmDialog(null,"INGIN KEMBALI KE FORM ?","KONFIRMASI",
            JOptionPane.YES_NO_CANCEL_OPTION);
        if(tanya==0){
            new DONASI().setVisible(true);//nama frame
            this.dispose();
        }
        else if(tanya==1){
            this.dispose();
        }
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CetakDonasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CetakDonasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CetakDonasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CetakDonasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CetakDonasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
