/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panti_asuhan;

import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author RIZKY ALFARIZI 18076091 
 * jangan lupa kerjain tugas sambil dengerin lagu kangen band
 */

public class DATA_AGENDA extends javax.swing.JFrame {

 Connection konek;
 public Statement cn;
 String tanggal,id,nama,lokasi;
 
 public void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Sukses Driver JDBC Ditemukan....!");
        try {
            String url =
            "jdbc:mysql://localhost/pantiasuhan?user=root&password=";
             konek = DriverManager.getConnection(url);
             cn=konek.createStatement();
             System.out.println("Sukses Koneksi...");
         } catch (SQLException se) {
            System.out.println(" Gagal Koneksi = " + se);
             System.exit(0);
     }
         } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(null, "Class Tidak ditemukan...Error: " + cnfe);
            System.exit(0);
 }
}  
public void tampildata(){
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID AGENDA");
    tabel.addColumn("NAMA AGENDA ");
    tabel.addColumn("LOKASI");
    tabel.addColumn("TANGGAL");
        
    try{
        String sql="Select * from agenda"; //perintah menampilkan isi tabel
        Statement stt=(Statement) konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_agenda"), //Sesuai nama tabel di database
            res.getString("nama_agenda"),
            res.getString("lokasi"),
            res.getString("tanggal_agenda")});
            jTable1.setModel(tabel);
        }
    }
    catch(Exception e){
                }
    }

public void clear(){
    jTextField1.setText("");
    jTextField2.setText("");
    jTextPane1.setText("");
    jDateChooser1.setDate(null);
    jTextField1.setEnabled(true);
}
 
    public DATA_AGENDA() {
        initComponents();
        koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(30, 155, 133));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 191, 26));

        jButton2.setBackground(new java.awt.Color(30, 155, 133));
        jButton2.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 191, 26));

        jButton3.setBackground(new java.awt.Color(30, 155, 133));
        jButton3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 191, 26));

        jButton4.setBackground(new java.awt.Color(30, 155, 133));
        jButton4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 191, 26));

        jButton5.setBackground(new java.awt.Color(30, 155, 133));
        jButton5.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CLOSE");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 191, 26));

        jButton6.setBackground(new java.awt.Color(30, 155, 133));
        jButton6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("TAMPILKAN DATA");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 191, 26));

        jButton7.setBackground(new java.awt.Color(30, 155, 133));
        jButton7.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CETAK");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 191, 26));

        jButton8.setBackground(new java.awt.Color(30, 178, 166));
        jButton8.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/home1.png"))); // NOI18N
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, -1, 70));

        jButton9.setBackground(new java.awt.Color(30, 178, 166));
        jButton9.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/search1.png"))); // NOI18N
        jButton9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 40, 50));

        jTextField3.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 191, 30));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel8.setText("TANGGAL AGENDA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jDateChooser1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 250, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel1.setText("ID AGENDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 250, 30));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel3.setText("NAMA AGENDA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jTextField2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 250, 30));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jLabel4.setText("LOKASI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jTable1.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID AGENDA", "NAMA AGENDA", "LOKASI", "TANGGAL AGENDA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 680, 130));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/LOGO.png"))); // NOI18N
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 70));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BAKTI   ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" LUHUR");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bakti Luhur peduli sesama");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel6.setBackground(new java.awt.Color(30, 178, 166));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 290, 620));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 178, 166));
        jLabel5.setText("DATA AGENDA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 178, 166));
        jLabel13.setText("____");
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 280, 60));

        jTextPane1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 250, 90));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 970, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID AGENDA");
    tabel.addColumn("NAMA AGENDA ");
    tabel.addColumn("LOKASI");
    tabel.addColumn("TANGGAL");
    
    try{
        String sql="Select*from agenda where id_agenda like '%"+
                jTextField3.getText()+"%' or nama_agenda like '%"+
                jTextField3.getText()+"%' or lokasi like '%"+
                jTextField3.getText()+"%' or tanggal_agenda like '%"+
                jTextField3.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_agenda"), //Sesuai nama tabel di database
            res.getString("nama_agenda"),
            res.getString("lokasi"),
            res.getString("tanggal_agenda")});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new MAINMENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      id=jTextField1.getText();
      nama=jTextField2.getText();
      lokasi=jTextPane1.getText(); 

    if (id.equals("")) {
        JOptionPane.showMessageDialog(null, "ID TIDAK BOLEH KOSONG");
        jTextField1.requestFocus();
    }else {
        try {
                String sql = "Insert Into agenda values(?,?,?,?)";
                PreparedStatement stat = konek.prepareStatement(sql);
                try {
                        stat.setString(1, id);
                        stat.setString(2, nama);
                        stat.setString(3, lokasi);
                        stat.setString(4, tanggal);
                        stat.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Data Tersimpan.....");
                    } catch (SQLException se) {
                        System.out.println("Gagal Menyimpan.." + se);
                        JOptionPane.showMessageDialog(null, "Yang Anda Masukkan Telah Ada..\nGagal Disimpan..Coba Lagi \npesan Error :\n");
                        jTextField1.requestFocus();
                    }
                } catch (Exception se) {
                }
            }

   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if(jDateChooser1.getDate()!=null){
            SimpleDateFormat tgl=new SimpleDateFormat("yyyy-MM-dd");
            tanggal = tgl.format(jDateChooser1.getDate());
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int table =jTable1.getSelectedRow();
        String a = jTable1.getValueAt(table, 0).toString(); //id 
        String b = jTable1.getValueAt(table, 1).toString(); //nama
        String c = jTable1.getValueAt(table, 2).toString(); //lokasi
        //tanggal
        try{
            java.util.Date tgl= new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable1.getValueAt(table,3));
            jDateChooser1.setDate(tgl);
        } catch (Exception se){
        }
        
        jTextField1.setText(a);
        jTextField2.setText(b);
        jTextPane1.setText(c);
        
        jTextField1.setEnabled(false);
        jTextField2.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // UPDATE DATA    
      id=jTextField1.getText();
      nama=jTextField2.getText();
      lokasi=jTextPane1.getText();
      
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Data tidak boleh kosong");
            jTextField1.requestFocus();
        }else{
            try{
                String sql="Update agenda set nama_agenda='"+nama+"',"
                        +"lokasi= '"+lokasi +"',"
                        +"tanggal_agenda = '"+tanggal+""
                        +"'where id_agenda= '"+id+"'";
                cn.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIUPDATE");   
            }
            catch (Exception se){
                JOptionPane.showMessageDialog(null, "GAGAL MENGUBAH DATA"+se);
                jTextField1.requestFocus();
            }
        }
        clear();
        tampildata();
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // DELETE DATA 
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Menghapus Data Ini?","Confirmation",
                JOptionPane.YES_NO_CANCEL_OPTION); //panel konfirmasi
        
        if(ok==0)
        {
            try{
                String sql="Delete from agenda where id_agenda='"+jTextField1.getText()+"'";
                PreparedStatement st=konek.prepareStatement(sql);
                st.executeUpdate();
                JOptionPane.showMessageDialog(null,"DELETE DATA SUKSES");
            }
            catch (Exception e){
            }
        }
        tampildata();
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tampildata();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID AGENDA");
    tabel.addColumn("NAMA AGENDA ");
    tabel.addColumn("LOKASI");
    tabel.addColumn("TANGGAL");
    
    try{
        String sql="Select*from agenda where id_agenda like '%"+
                jTextField3.getText()+"%' or nama_agenda like '%"+
                jTextField3.getText()+"%' or lokasi like '%"+
                jTextField3.getText()+"%' or tanggal_agenda like '%"+
                jTextField3.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_agenda"), //Sesuai nama tabel di database
            res.getString("nama_agenda"),
            res.getString("lokasi"),
            res.getString("tanggal_agenda")});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
    }
    
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int tanya=JOptionPane.showConfirmDialog(null,"INGIN MENCETAK DATA ?","TANYA",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(tanya==0){
            new CetakAgenda().setVisible(true);
            this.dispose();
        }
        else if(tanya==1){
            new DATA_AGENDA().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATA_AGENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATA_AGENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATA_AGENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATA_AGENDA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATA_AGENDA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
