/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panti_asuhan;

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class DONASI extends javax.swing.JFrame {

 Connection konek;
 public Statement cn;
 public Statement res;
 public Statement stat;
 String id_don,id_peg,nama_don,nama_peg,bentuk,ket;
 
 public void koneksi(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        System.out.println("Sukses Driver JDBC Ditemukan....!");
        try {
            String url =
            "jdbc:mysql://localhost/pantiasuhan?user=root&password=";
             konek = DriverManager.getConnection(url);
             cn=konek.createStatement();
             System.out.println("Sukses Koneksi...");
         } catch (SQLException se) {
            System.out.println(" Gagal Koneksi = " + se);
             System.exit(0);
     }
         } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(null, "Class Tidak ditemukan...Error: " + cnfe);
            System.exit(0);
 }
}  
 
public void clear(){
    jTextField1.setText("");
    jTextField2.setText("");
    buttonGroup1.clearSelection();
    jTextField3.setText("");
    jTextField4.setText("");
    jComboBox1.setSelectedIndex(0);
    jComboBox2.setSelectedIndex(0);
    jTextField1.setEnabled(true);
}
 
public void tampildata(){
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID DONATUR");
    tabel.addColumn("NAMA DONATUR ");
    tabel.addColumn("ID PEGAWAI");
    tabel.addColumn("NAMA PEGAWAI");
    tabel.addColumn("BENTUK");
    tabel.addColumn("KETERANGAN");
    
    try{
        String sql="Select * from donasi"; //perintah menampilkan isi tabe;
        Statement stt=(Statement) konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_donatur"), //Sesuai nama tabel di database
            res.getString("nama_donatur"),
            res.getString("id_pegawai"),
            res.getString("nama_pegawai"),
            res.getString("bentuk"),
            res.getString("keterangan")});
            jTable1.setModel(tabel);
        }
    }
    catch(Exception e){
                }
    }

 public void dataComboBox1(){
     try{
         String query="select *from donatur";
         Statement stat=konek.createStatement();
         ResultSet res=stat.executeQuery(query);
         while (res.next()){
             jComboBox1.addItem(res.getString("id_donatur"));
             
         }
         res.last();
         res.first();
     } catch (Exception e){
    }
 }
 
 private void isiTextField1(){
     String code = (String) jComboBox1.getSelectedItem();
 try {

        String sql = "select * from donatur WHERE id_donatur='"+code +"'";
        Statement stat = konek.createStatement();
        ResultSet rs=stat.executeQuery(sql);


          while (rs.next()){
           jTextField1.setText(rs.getString("nama_donatur"));
       }
 }
 
 catch(Exception e){
    e.printStackTrace();

 } 
 }
 
public void dataComboBox2(){
     koneksi();
     try{
         String query="select *from pegawai";
         Statement stat=konek.createStatement();
         ResultSet res=stat.executeQuery(query);
         while (res.next()){
             jComboBox2.addItem(res.getString("id_pegawai"));
         }
         res.last();
         res.first();
     } catch (Exception e){
    }
 }

 private void isiTextField2(){
     String code = (String) jComboBox2.getSelectedItem();
 try {

        String sql = "select * from pegawai WHERE id_pegawai='"+ code +"'";
        Statement stat = konek.createStatement();
        ResultSet rs=stat.executeQuery(sql);

          while (rs.next()){
           jTextField2.setText(rs.getString("nama_pegawai"));
       }
 }
 catch(Exception e){
    e.printStackTrace();
 } 
 }

    public DONASI() {
        initComponents();
        koneksi();
        dataComboBox1();
        dataComboBox2();
        this.setLocationRelativeTo(getRootPane());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setText("NAMA DONATUR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jTextField1.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 250, -1));

        jTable1.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID DONATUR", "NAMA DONATUR", "ID PEGAWAI", "NAMA PEGAWAI", "BENTUK", "KETERANGAN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 483, 700, 116));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel6.setText("BENTUK");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel7.setText("KETERANGAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel8.setText("ID PEGAWAI");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel9.setText("NAMA PEGAWAI");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("ID DONATUR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        jTextField3.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 250, -1));

        jTextField2.setFont(new java.awt.Font("Swis721 BT", 0, 16)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 250, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/LOGO.png"))); // NOI18N
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 70));

        jLabel11.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BAKTI   ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" LUHUR");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bakti Luhur peduli sesama");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel14.setBackground(new java.awt.Color(30, 178, 166));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 290, 620));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Dubai", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 178, 166));
        jLabel16.setText("DATA DONASI");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 178, 166));
        jLabel17.setText("____");
        jLabel17.setToolTipText("");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 280, 60));

        jButton1.setBackground(new java.awt.Color(30, 155, 133));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAVE");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 191, 26));

        jButton4.setBackground(new java.awt.Color(30, 155, 133));
        jButton4.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 191, 26));

        jButton5.setBackground(new java.awt.Color(30, 155, 133));
        jButton5.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CLOSE");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 191, 26));

        jButton6.setBackground(new java.awt.Color(30, 155, 133));
        jButton6.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("TAMPILKAN DATA");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 191, 26));

        jButton7.setBackground(new java.awt.Color(30, 155, 133));
        jButton7.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CETAK");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 191, 26));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/home1.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 70, 70));

        jButton9.setBackground(new java.awt.Color(30, 155, 133));
        jButton9.setFont(new java.awt.Font("Dubai", 1, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panti_asuhan/search1.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 430, 50, 50));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 191, 30));

        jComboBox2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---ID PEGAWAI---" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 250, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jRadioButton1.setText("LAINNYA");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jRadioButton2.setText("UANG");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jRadioButton3.setText("BARANG");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---ID DONATUR---" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 250, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 960, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID DONATUR");
    tabel.addColumn("NAMA DONATUR");
    tabel.addColumn("ID PEGAWAI");
    tabel.addColumn("NAMA PEGAWAI");
    tabel.addColumn("BENTUK");
    tabel.addColumn("KETERANGAN");
    
    try{
        String sql="Select*from donasi where id_donatur like '%"+
                jTextField4.getText()+"%' or nama_donatur like '%"+
                jTextField4.getText()+"%' or id_pegawai like '%"+
                jTextField4.getText()+"%' or nama_pegawai like '%"+
                jTextField4.getText()+"%' or bentuk like '%"+
                jTextField4.getText()+"%' or keterangan like '%"+
                jTextField4.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_donatur"), //Sesuai nama tabel di database
            res.getString("nama_donatur"),
            res.getString("id_pegawai"),
            res.getString("nama_pegawai"),
            res.getString("bentuk"),
            res.getString("keterangan")});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new MAINMENU().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        isiTextField2();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      // TODO add your handling code here:
      isiTextField1();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        tampildata();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int table =jTable1.getSelectedRow();
        String a = jTable1.getValueAt(table, 0).toString(); //id
        String b = jTable1.getValueAt(table, 1).toString(); //nama
        String c = jTable1.getValueAt(table, 2).toString(); //jk
        String d = jTable1.getValueAt(table, 3).toString(); //jk
        String e = jTable1.getValueAt(table, 4).toString(); //tempatlahir
        String f = jTable1.getValueAt(table, 5).toString();//alamat
        
        jComboBox1.setSelectedItem(a);
        jTextField1.setText(b);
        jComboBox2.setSelectedItem(c);
        jTextField2.setText(d);
        if("UANG".equals(e)){
            jRadioButton1.setSelected(true);
        }else{
            jRadioButton2.setSelected(true);
        }
        if("BARANG".equals(e)){
            jRadioButton1.setSelected(true);
        }else{
            jRadioButton2.setSelected(true);
        }
        if("LAINNYA".equals(e)){
            jRadioButton1.setSelected(true);
        }else{
            jRadioButton2.setSelected(true);
        }
        jTextField3.setText(f);
                
        jTextField2.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        id_don=String.valueOf(jComboBox1.getSelectedItem());
        nama_don=jTextField1.getText();
        id_peg = String.valueOf(jComboBox2.getSelectedItem());
        nama_peg=jTextField2.getText();
        ket=jTextField3.getText();
        if (jRadioButton1.isSelected())
        {bentuk=jRadioButton1.getText();}
        else if(jRadioButton2.isSelected())
        {bentuk=jRadioButton2.getText();}
        else if(jRadioButton3.isSelected())
        {bentuk=jRadioButton3.getText();}
        else
        {bentuk="";}

        //simpan
        if (id_don.equals("")|(id_peg.equals("")|id_don.equals("")| nama_don.equals("") |
            bentuk.equals("")|ket.equals(""))){
        JOptionPane.showMessageDialog(null, "DATA TIDAK BOLEH KOSONG");
        jTextField1.requestFocus();
        } else {
            try {
                String sql="Insert into donasi values(?,?,?,?,?,?)";
                PreparedStatement stat=konek.prepareStatement (sql);
                try{
                    stat.setString(1,id_don);
                    stat.setString(2,nama_don);
                    stat.setString(3,id_peg);
                    stat.setString(4,nama_peg);
                    stat.setString(5,bentuk);
                    stat.setString(6,ket);
                    stat.executeUpdate();
                    JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");
                } catch (SQLException se) {
                    System.out.println("Gagal Menyimpan.." + se);
                    JOptionPane.showMessageDialog(null, "Yang Anda Masukkan Telah Ada..\nGagal Disimpan..Coba Lagi \npesan Error :\n" +se);
                    jTextField1.requestFocus();
                }
            } catch (Exception se) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID DONATUR");
    tabel.addColumn("NAMA DONATUR");
    tabel.addColumn("ID PEGAWAI");
    tabel.addColumn("NAMA PEGAWAI");
    tabel.addColumn("BENTUK");
    tabel.addColumn("KETERANGAN");
    
    try{
        String sql="Select*from donasi where id_donatur like '%"+
                jTextField4.getText()+"%' or nama_donatur like '%"+
                jTextField4.getText()+"%' or id_pegawai like '%"+
                jTextField4.getText()+"%' or nama_pegawai like '%"+
                jTextField4.getText()+"%' or bentuk like '%"+
                jTextField4.getText()+"%' or keterangan like '%"+
                jTextField4.getText()+"%'";
        Statement stt=konek.createStatement();
        ResultSet res=stt.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{
            res.getString("id_donatur"), //Sesuai nama tabel di database
            res.getString("nama_donatur"),
            res.getString("id_pegawai"),
            res.getString("nama_pegawai"),
            res.getString("bentuk"),
            res.getString("keterangan")});
            jTable1.setModel(tabel);
        }
    }
    catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       // TODO add your handling code here:
        int tanya=JOptionPane.showConfirmDialog(null,"INGIN MENCETAK DATA ?","TANYA",
                JOptionPane.YES_NO_CANCEL_OPTION);
        if(tanya==0){
            new CetakDonasi().setVisible(true);
            this.dispose();
        }
        else if(tanya==1){
            new DONASI().setVisible(true);
            this.dispose();
        }    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DONASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DONASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DONASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DONASI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DONASI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
